Limit json to < 2.5.0 on Windows Ruby 2.0.
2.5.1 is declared as compatible with Ruby >= 2.0, but actually fails to
compile with an undefined reference to `rb_funcallv` on Windows:
https://github.com/tzinfo/tzinfo/runs/1664656059#step:3:757